### ISSUE TITLE
where to config the REACT_APP_API_KEY ?

### ISSUE THREAD

**Issue by baldonazionale** [Isaac-alencar/moviebox#1]
the key used in this API
https://api.themoviedb.org/3/movie/popular?api_key=undefined

**Comment by Isaac-alencar** [comment]
Hey @baldonazionale, you have to generate an api key on [tmdb](https://developers.themoviedb.org/3)

then you must create an  `.env` file in the root of project with the following content:
```environment
REACT_APP_API_KEY=<your api key>
```
feel free to create an PR adding the instructions for how to setup and start the project on `README.md`

**Comment by baldonazionale** [comment]
> Hey @baldonazionale, you have to generate an api key on [tmdb](https://developers.themoviedb.org/3)
> 
> then you must create an `.env` file in the root of project with the following content:
> 
> ```
> REACT_APP_API_KEY=<your api key>
> ```
> 
> feel free to create an PR adding the instructions for how to setup and start the project on `README.md`

not sure if I did correctly (I never did a PR)
[more-readme-info-1](https://github.com/Isaac-alencar/moviebox/pull/2)

**Comment by baldonazionale** [comment]
this should be better:
https://github.com/Isaac-alencar/moviebox/pull/3
